# Generated by Django 4.1.6 on 2023-02-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplecounter',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
