# Generated by Django 4.1.6 on 2023-02-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy_app', '0002_alter_peoplecounter_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplecounter',
            name='sensor',
        ),
    ]
