# Generated by Django 4.1.6 on 2023-02-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy_app', '0003_remove_peoplecounter_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplecounter',
            name='sensor_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
