# Generated by Django 4.1.6 on 2023-02-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy_app', '0004_peoplecounter_sensor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplecounter',
            name='sensor_name',
            field=models.CharField(max_length=50),
        ),
    ]
